<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<AssemblyVersion>1.0</AssemblyVersion>
	<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="EMTDisplay\**" />
    <Compile Remove="MeleeThirdPerson\**" />
    <EmbeddedResource Remove="EMTDisplay\**" />
    <EmbeddedResource Remove="MeleeThirdPerson\**" />
    <None Remove="EMTDisplay\**" />
    <None Remove="MeleeThirdPerson\**" />
  </ItemGroup>
</Project>
