namespace ExternalMeleeTool;

/// <summary>A static class that contains important pointers to melee's memory.</summary>
public static class MeleeConstants {
    // these are all offsets from GALE01!!!!
    public const nint CAM_START = 0x453040;
    public const nint CAM_TYPE = 0x452C6F;
    public const nint PLAYER_ONE = 0x453080;
    public const nint PLAYER_TWO = 0x453F10;
    public const nint PLAYER_THREE = 0x454DA0;
    public const nint PLAYER_FOUR = 0x455C30;
    public const nint PAUSE_BIT = 0x479D68;

    public const nint START_MELEE_RULES = 0x46DB68;

    public const nint MINOR_SCENE = 0x479D30;
    public const nint MAJOR_SCENE = 0x479D33;
    public const byte MAJOR_SCENE_MAINMENU = 0;
    public const byte MAJOR_SCENE_STAGESELECT = 1;
    public const byte MAJOR_SCENE_INGAME = 2;

    // size of GC memory, where all code lies for any GC game
    public const nint RAM_SIZE = 0x02000000;
    public const nuint ROM_SIZE = 0x80000000;

    public const nint FTPART_SIZE = 0x10;

    // what is R13?
    public const nint R13 = 0x4DB6A0;


    /* in a regular workflow ->
     * stinfo = GetPtr(STAGE_INFO)
     * coll_data = GetPtr(stinfo + 0x6AC)
     */
    public const nint STAGE_INFO = 0x49E6C8;
}
/// <summary>A static class that contains important pointers to Slippi Netplay memory.</summary>
public static class SlippiConstants {
    // thanks, Altafen!
    public const long ONLINE_DATA_BLOCK = MeleeConstants.R13 - 0x49E4;
}
[Flags]
public enum HSDPadButton : uint {
    None         = 0,

    DPadLeft     = 0x0001,
    DPadRight    = 0x0002,
    DPadDown     = 0x0004,
    DPadUp       = 0x0008,

    TriggerZ     = 0x0010,
    TriggerR     = 0x0020,
    TriggerL     = 0x0040,

    A            = 0x0100,
    B            = 0x0200,
    X            = 0x0400,
    Y            = 0x0800,
    Start        = 0x1000,

    Up           = 0x10000,
    Down         = 0x20000,
    Left         = 0x40000,
    Right        = 0x80000,
}
public enum CameraKind : byte {
    Normal = 0x00,
    Develop = 0x08
}
public enum FighterMemorySlot : long {
    IndexOne = MeleeConstants.PLAYER_ONE,
    IndexTwo = MeleeConstants.PLAYER_TWO,
    IndexThree = MeleeConstants.PLAYER_THREE,
    IndexFour = MeleeConstants.PLAYER_FOUR
}

public enum SlotTeam {
    Red    = 0,
    Blue   = 1,
    Green  = 2
}
// unsure of the other kinds...
public enum SlotKind {
    Human  = 0x0,
    CPU    = 0x1,
    Demo   = 0x2,
    None   = 0x3,
    Boss   = 0x4
}

// hal smoking crack to make these different as per usual.
public enum CKind
{
    Captain             = 0x00,
    Donkey              = 0x01,
    Fox                 = 0x02,
    GameWatch           = 0x03,
    Kirby               = 0x04,
    Koopa               = 0x05, // bowser
    Link                = 0x06,
    Luigi               = 0x07,
    Mario               = 0x08,
    Marth               = 0x09,
    Mewtwo              = 0x0A,
    Ness                = 0x0B,
    Peach               = 0x0C,
    Pikachu             = 0x0D,
    PopoNana            = 0x0E,
    Jigglypuff          = 0x0F, // but not purin?? hal???
    Samus               = 0x10,
    Yoshi               = 0x11,
    Zelda               = 0x12,
    Sheik               = 0x13,
    Falco               = 0x14,
    YoungLink           = 0x15,
    DrMario             = 0x16,
    Roy                 = 0x17,
    Pichu               = 0x18,
    Ganondorf           = 0x19,

    PlayableCount       = 0x1A,

    MasterHand          = PlayableCount,
    WireframeMale       = 0x1B,
    WireframeFemale     = 0x1C,
    GigaBowser          = 0x1D,
    CrazyHand           = 0x1E,
    Sandbag             = 0x1F,
    Popo                = 0x20,

    None                = 0x21,
    Max                 = None
}

public enum ExternalStageId {
    DUMMY = 0,
    TEST = 1,
    IZUMI = 2, // FoD
    PSTADIUM = 3,
    CASTLE = 4,
    KONGO = 5,
    ZEBES = 6,
    CORNERIA = 7,
    STORY = 8,
    ONETT = 9,
    MUTECITY = 10,
    RCRUISE = 11,
    GARDEN = 12,
    GREATBAY = 13,
    SHRINE = 14, // Temple
    KRAID = 15, // Depths
    YOSTER = 16, // Yoshi's Island
    GREENS = 17,
    FOURSIDE = 18,
    INISHIE1 = 19, // Kingdom 1
    INISHIE2 = 20, // Kingdom 2
    AKANEIA = 21,  // debug only?
    VENOM = 22,
    PURA = 23, // Poke Floats
    BIGBLUE = 24,
    ICEMT = 25, // Ice Mountain
    ICETOP = 26, // debug only?
    FLATZONE = 27,
    OLD_PPP = 28, // Dreamland 64
    OLD_YOSH = 29, // Yoshi's Island
    OLD_KONG = 30,
    BATTLE = 31,
    LAST = 32,

    // T = Training, plus character name
    TMARIO = 33,
    TCAPTAIN = 34,
    TCLINK = 35,
    TDONKEY = 36,
    TDRMARIO = 37,
    TFALCO = 38,
    TFOX = 39,
    TICECLIM = 40,
    TKIRBY = 41,
    TKOOPA = 42,
    TLINK = 43,
    TLUIGI = 44,
    TMARS = 45,
    TMEWTWO = 46,
    TNESS = 47,
    TPEACH = 48,
    TPICHU = 49,
    TPIKACHU = 50,
    TPURIN = 51,
    TSAMUS = 52,
    TSEAK = 53,
    TYOSHI = 54,
    TZELDA = 55,
    TGAMEWAT = 56,
    TEMBLEM = 57,
    TGANON = 58,

    _1_1KINOKO = 59, // Adventure Kingdom
    _1_2CASTLE = 60,
    _2_1KONGO = 61,
    _2_2GARDEN = 62,
    _3_1MEIKYU = 63, // Underground Maze
    _3_2SHRINE = 64,
    _4_1ZEBES = 65,
    _4_2DASSYUT = 66, // Brinstar Escape
    _5_1GREENS = 67,
    _5_2GREENS = 68,
    _5_3GREENS = 69,
    _6_1CORNERI = 70,
    _6_2CORNERI = 71,
    _7PSTADIUM = 72,
    _8_1BBROUTE = 73, // F-Zero GP
    _8_2MUTECIT = 74,
    _9_1ONETT = 75,
    _10_1ICEMT = 76,
    _10_2 = 77,
    _11_1BATTLE = 78,
    _11_2BATTLE = 79,
    _12_1LAST = 80,
    _12_2LAST = 81,

    TUKISUSUME = 82, // Race to finish
    FIGUREGET = 83, // trophies
    HOMERUN = 84,
    HEAL = 85 // All-Star rest
}

public enum FtAnimState {
    ASID_DEADDOWN,
    ASID_DEADLEFT,
    ASID_DEADRIGHT,
    ASID_DEADUP,
    ASID_DEADUPSTAR,
    ASID_DEADUPSTARICE,
    ASID_DEADUPFALL,
    ASID_DEADUPFALLHITCAMERA,
    ASID_DEADUPFALLHITCAMERAFLAT,
    ASID_DEADUPFALLICE,
    ASID_DEADUPFALLHITCAMERAICE,
    ASID_SLEEP,
    ASID_REBIRTH,
    ASID_REBIRTHWAIT,
    ASID_WAIT,
    ASID_WALKSLOW,
    ASID_WALKMIDDLE,
    ASID_WALKFAST,
    ASID_TURN,
    ASID_TURNRUN,
    ASID_DASH,
    ASID_RUN,
    ASID_RUNDIRECT,
    ASID_RUNBRAKE,
    ASID_KNEEBEND,
    ASID_JUMPF,
    ASID_JUMPB,
    ASID_JUMPAERIALF,
    ASID_JUMPAERIALB,
    ASID_FALL,
    ASID_FALLF,
    ASID_FALLB,
    ASID_FALLAERIAL,
    ASID_FALLAERIALF,
    ASID_FALLAERIALB,
    ASID_FALLSPECIAL,
    ASID_FALLSPECIALF,
    ASID_FALLSPECIALB,
    ASID_DAMAGEFALL,
    ASID_SQUAT,
    ASID_SQUATWAIT,
    ASID_SQUATRV,
    ASID_LANDING,
    ASID_LANDINGFALLSPECIAL,
    ASID_ATTACK11,
    ASID_ATTACK12,
    ASID_ATTACK13,
    ASID_ATTACK100START,
    ASID_ATTACK100LOOP,
    ASID_ATTACK100END,
    ASID_ATTACKDASH,
    ASID_ATTACKS3HI,
    ASID_ATTACKS3HIS,
    ASID_ATTACKS3S,
    ASID_ATTACKS3LWS,
    ASID_ATTACKS3LW,
    ASID_ATTACKHI3,
    ASID_ATTACKLW3,
    ASID_ATTACKS4HI,
    ASID_ATTACKS4HIS,
    ASID_ATTACKS4S,
    ASID_ATTACKS4LWS,
    ASID_ATTACKS4LW,
    ASID_ATTACKHI4,
    ASID_ATTACKLW4,
    ASID_ATTACKAIRN,
    ASID_ATTACKAIRF,
    ASID_ATTACKAIRB,
    ASID_ATTACKAIRHI,
    ASID_ATTACKAIRLW,
    ASID_LANDINGAIRN,
    ASID_LANDINGAIRF,
    ASID_LANDINGAIRB,
    ASID_LANDINGAIRHI,
    ASID_LANDINGAIRLW,
    ASID_DAMAGEHI1,
    ASID_DAMAGEHI2,
    ASID_DAMAGEHI3,
    ASID_DAMAGEN1,
    ASID_DAMAGEN2,
    ASID_DAMAGEN3,
    ASID_DAMAGELW1,
    ASID_DAMAGELW2,
    ASID_DAMAGELW3,
    ASID_DAMAGEAIR1,
    ASID_DAMAGEAIR2,
    ASID_DAMAGEAIR3,
    ASID_DAMAGEFLYHI,
    ASID_DAMAGEFLYN,
    ASID_DAMAGEFLYLW,
    ASID_DAMAGEFLYTOP,
    ASID_DAMAGEFLYROLL,
    ASID_LIGHTGET,
    ASID_HEAVYGET,
    ASID_LIGHTTHROWF,
    ASID_LIGHTTHROWB,
    ASID_LIGHTTHROWHI,
    ASID_LIGHTTHROWLW,
    ASID_LIGHTTHROWDASH,
    ASID_LIGHTTHROWDROP,
    ASID_LIGHTTHROWAIRF,
    ASID_LIGHTTHROWAIRB,
    ASID_LIGHTTHROWAIRHI,
    ASID_LIGHTTHROWAIRLW,
    ASID_HEAVYTHROWF,
    ASID_HEAVYTHROWB,
    ASID_HEAVYTHROWHI,
    ASID_HEAVYTHROWLW,
    ASID_LIGHTTHROWF4,
    ASID_LIGHTTHROWB4,
    ASID_LIGHTTHROWHI4,
    ASID_LIGHTTHROWLW4,
    ASID_LIGHTTHROWAIRF4,
    ASID_LIGHTTHROWAIRB4,
    ASID_LIGHTTHROWAIRHI4,
    ASID_LIGHTTHROWAIRLW4,
    ASID_HEAVYTHROWF4,
    ASID_HEAVYTHROWB4,
    ASID_HEAVYTHROWHI4,
    ASID_HEAVYTHROWLW4,
    ASID_SWORDSWING1,
    ASID_SWORDSWING3,
    ASID_SWORDSWING4,
    ASID_SWORDSWINGDASH,
    ASID_BATSWING1,
    ASID_BATSWING3,
    ASID_BATSWING4,
    ASID_BATSWINGDASH,
    ASID_PARASOLSWING1,
    ASID_PARASOLSWING3,
    ASID_PARASOLSWING4,
    ASID_PARASOLSWINGDASH,
    ASID_HARISENSWING1,
    ASID_HARISENSWING3,
    ASID_HARISENSWING4,
    ASID_HARISENSWINGDASH,
    ASID_STARRODSWING1,
    ASID_STARRODSWING3,
    ASID_STARRODSWING4,
    ASID_STARRODSWINGDASH,
    ASID_LIPSTICKSWING1,
    ASID_LIPSTICKSWING3,
    ASID_LIPSTICKSWING4,
    ASID_LIPSTICKSWINGDASH,
    ASID_ITEMPARASOLOPEN,
    ASID_ITEMPARASOLFALL,
    ASID_ITEMPARASOLFALLSPECIAL,
    ASID_ITEMPARASOLDAMAGEFALL,
    ASID_LGUNSHOOT,
    ASID_LGUNSHOOTAIR,
    ASID_LGUNSHOOTEMPTY,
    ASID_LGUNSHOOTAIREMPTY,
    ASID_FIREFLOWERSHOOT,
    ASID_FIREFLOWERSHOOTAIR,
    ASID_ITEMSCREW,
    ASID_ITEMSCREWAIR,
    ASID_DAMAGESCREW,
    ASID_DAMAGESCREWAIR,
    ASID_ITEMSCOPESTART,
    ASID_ITEMSCOPERAPID,
    ASID_ITEMSCOPEFIRE,
    ASID_ITEMSCOPEEND,
    ASID_ITEMSCOPEAIRSTART,
    ASID_ITEMSCOPEAIRRAPID,
    ASID_ITEMSCOPEAIRFIRE,
    ASID_ITEMSCOPEAIREND,
    ASID_ITEMSCOPESTARTEMPTY,
    ASID_ITEMSCOPERAPIDEMPTY,
    ASID_ITEMSCOPEFIREEMPTY,
    ASID_ITEMSCOPEENDEMPTY,
    ASID_ITEMSCOPEAIRSTARTEMPTY,
    ASID_ITEMSCOPEAIRRAPIDEMPTY,
    ASID_ITEMSCOPEAIRFIREEMPTY,
    ASID_ITEMSCOPEAIRENDEMPTY,
    ASID_LIFTWAIT,
    ASID_LIFTWALK1,
    ASID_LIFTWALK2,
    ASID_LIFTTURN,
    ASID_GUARDON,
    ASID_GUARD,
    ASID_GUARDOFF,
    ASID_GUARDSETOFF,
    ASID_GUARDREFLECT,
    ASID_DOWNBOUNDU,
    ASID_DOWNWAITU,
    ASID_DOWNDAMAGEU,
    ASID_DOWNSTANDU,
    ASID_DOWNATTACKU,
    ASID_DOWNFOWARDU,
    ASID_DOWNBACKU,
    ASID_DOWNSPOTU,
    ASID_DOWNBOUNDD,
    ASID_DOWNWAITD,
    ASID_DOWNDAMAGED,
    ASID_DOWNSTANDD,
    ASID_DOWNATTACKD,
    ASID_DOWNFOWARDD,
    ASID_DOWNBACKD,
    ASID_DOWNSPOTD,
    ASID_PASSIVE,
    ASID_PASSIVESTANDF,
    ASID_PASSIVESTANDB,
    ASID_PASSIVEWALL,
    ASID_PASSIVEWALLJUMP,
    ASID_PASSIVECEIL,
    ASID_SHIELDBREAKFLY,
    ASID_SHIELDBREAKFALL,
    ASID_SHIELDBREAKDOWNU,
    ASID_SHIELDBREAKDOWND,
    ASID_SHIELDBREAKSTANDU,
    ASID_SHIELDBREAKSTANDD,
    ASID_FURAFURA,
    ASID_CATCH,
    ASID_CATCHPULL,
    ASID_CATCHDASH,
    ASID_CATCHDASHPULL,
    ASID_CATCHWAIT,
    ASID_CATCHATTACK,
    ASID_CATCHCUT,
    ASID_THROWF,
    ASID_THROWB,
    ASID_THROWHI,
    ASID_THROWLW,
    ASID_CAPTUREPULLEDHI,
    ASID_CAPTUREWAITHI,
    ASID_CAPTUREDAMAGEHI,
    ASID_CAPTUREPULLEDLW,
    ASID_CAPTUREWAITLW,
    ASID_CAPTUREDAMAGELW,
    ASID_CAPTURECUT,
    ASID_CAPTUREJUMP,
    ASID_CAPTURENECK,
    ASID_CAPTUREFOOT,
    ASID_ESCAPEF,
    ASID_ESCAPEB,
    ASID_ESCAPE,
    ASID_ESCAPEAIR,
    ASID_REBOUNDSTOP,
    ASID_REBOUND,
    ASID_THROWNF,
    ASID_THROWNB,
    ASID_THROWNHI,
    ASID_THROWNLW,
    ASID_THROWNLWWOMEN,
    ASID_PASS,
    ASID_OTTOTTO,
    ASID_OTTOTTOWAIT,
    ASID_FLYREFLECTWALL,
    ASID_FLYREFLECTCEIL,
    ASID_STOPWALL,
    ASID_STOPCEIL,
    ASID_MISSFOOT,
    ASID_CLIFFCATCH,
    ASID_CLIFFWAIT,
    ASID_CLIFFCLIMBSLOW,
    ASID_CLIFFCLIMBQUICK,
    ASID_CLIFFATTACKSLOW,
    ASID_CLIFFATTACKQUICK,
    ASID_CLIFFESCAPESLOW,
    ASID_CLIFFESCAPEQUICK,
    ASID_CLIFFJUMPSLOW1,
    ASID_CLIFFJUMPSLOW2,
    ASID_CLIFFJUMPQUICK1,
    ASID_CLIFFJUMPQUICK2,
    ASID_APPEALR,
    ASID_APPEALL,
    ASID_SHOULDEREDWAIT,
    ASID_SHOULDEREDWALKSLOW,
    ASID_SHOULDEREDWALKMIDDLE,
    ASID_SHOULDEREDWALKFAST,
    ASID_SHOULDEREDTURN,
    ASID_THROWNFF,
    ASID_THROWNFB,
    ASID_THROWNFHI,
    ASID_THROWNFLW,
    ASID_CAPTURECAPTAIN,
    ASID_CAPTUREYOSHI,
    ASID_YOSHIEGG,
    ASID_CAPTUREKOOPA,
    ASID_CAPTUREDAMAGEKOOPA,
    ASID_CAPTUREWAITKOOPA,
    ASID_THROWNKOOPAF,
    ASID_THROWNKOOPAB,
    ASID_CAPTUREKOOPAAIR,
    ASID_CAPTUREDAMAGEKOOPAAIR,
    ASID_CAPTUREWAITKOOPAAIR,
    ASID_THROWNKOOPAAIRF,
    ASID_THROWNKOOPAAIRB,
    ASID_CAPTUREKIRBY,
    ASID_CAPTUREWAITKIRBY,
    ASID_THROWNKIRBYSTAR,
    ASID_THROWNCOPYSTAR,
    ASID_THROWNKIRBY,
    ASID_BARRELWAIT,
    ASID_BURY,
    ASID_BURYWAIT,
    ASID_BURYJUMP,
    ASID_DAMAGESONG,
    ASID_DAMAGESONGWAIT,
    ASID_DAMAGESONGRV,
    ASID_DAMAGEBIND,
    ASID_CAPTUREMEWTWO,
    ASID_CAPTUREMEWTWOAIR,
    ASID_THROWNMEWTWO,
    ASID_THROWNMEWTWOAIR,
    ASID_WARPSTARJUMP,
    ASID_WARPSTARFALL,
    ASID_HAMMERWAIT,
    ASID_HAMMERWALK,
    ASID_HAMMERTURN,
    ASID_HAMMERKNEEBEND,
    ASID_HAMMERFALL,
    ASID_HAMMERJUMP,
    ASID_HAMMERLANDING,
    ASID_KINOKOGIANTSTART,
    ASID_KINOKOGIANTSTARTAIR,
    ASID_KINOKOGIANTEND,
    ASID_KINOKOGIANTENDAIR,
    ASID_KINOKOSMALLSTART,
    ASID_KINOKOSMALLSTARTAIR,
    ASID_KINOKOSMALLEND,
    ASID_KINOKOSMALLENDAIR,
    ASID_ENTRY,
    ASID_ENTRYSTART,
    ASID_ENTRYEND,
    ASID_DAMAGEICE,
    ASID_DAMAGEICEJUMP,
    ASID_CAPTUREMASTERHAND,
    ASID_CAPTUREDAMAGEMASTERHAND,
    ASID_CAPTUREWAITMASTERHAND,
    ASID_THROWNMASTERHAND,
    ASID_CAPTUREKIRBYYOSHI,
    ASID_KIRBYYOSHIEGG,
    ASID_CAPTURELEADEAD,
    ASID_CAPTURELIKELIKE,
    ASID_DOWNREFLECT,
    ASID_CAPTURECRAZYHAND,
    ASID_CAPTUREDAMAGECRAZYHAND,
    ASID_CAPTUREWAITCRAZYHAND,
    ASID_THROWNCRAZYHAND,
    ASID_BARRELCANNONWAIT
}

public enum FtPart {
    FtPart_TopN,
    FtPart_TransN,
    FtPart_XRotN,
    FtPart_YRotN,
    FtPart_HipN,
    FtPart_WaistN,
    FtPart_LLegJA,
    FtPart_LLegJ,
    FtPart_LKneeJ,
    FtPart_LFootJA,
    FtPart_LFootJ,
    FtPart_RLegJA,
    FtPart_RLegJ,
    FtPart_RKneeJ,
    FtPart_RFootJA,
    FtPart_RFootJ,
    FtPart_BustN,
    FtPart_LShoulderN,
    FtPart_LShoulderJA,
    FtPart_LShoulderJ,
    FtPart_LArmJ,
    FtPart_LHandN,
    FtPart_L1stNa,
    FtPart_L1stNb,
    FtPart_L2ndNa,
    FtPart_L2ndNb,
    FtPart_L3rdNa,
    FtPart_L3rdNb,
    FtPart_L4thNa,
    FtPart_L4thNb,
    FtPart_LThumbNa,
    FtPart_LThumbNb,
    FtPart_LHandNb,
    FtPart_NeckN,
    FtPart_HeadN,
    FtPart_RShoulderN,
    FtPart_RShoulderJA,
    FtPart_RShoulderJ,
    FtPart_RArmJ,
    FtPart_RHandN,
    FtPart_R1stNa,
    FtPart_R1stNb,
    FtPart_R2ndNa,
    FtPart_R2ndNb,
    FtPart_R3rdNa,
    FtPart_R3rdNb,
    FtPart_R4thNa,
    FtPart_R4thNb,
    FtPart_RThumbNa,
    FtPart_RThumbNb,
    FtPart_RHandNb,
    FtPart_ThrowN,
    FtPart_TransN2,
    FtPart_109 = 109,
}

public enum CommonBone : uint {
    TopN,
    TransN,
    XRotN,
    YRotN,
    HipN,
    WaistN,
    NeckN   = 0x22,
    HeadN   = 0x23,
    ThrowN  = 0x35,
    Extra   = 0x36
}